#!/usr/bin/ruby

require 'date'

POSTS_DIR = '_posts/'

talk = ARGV[0]

File.open(POSTS_DIR + Date.today.strftime("%Y-%m-%d-") + post + '.md', 'w') {|f| f.write(
  "---\nlayout: talk\nsection-type: talk\ntitle: Title\ntech: Tech\npermalink: link\n---")
}

puts('[+] Created ' + talk + ' talk')
